/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SnakeGame;

import SnakeGame.gamelogic.Gameplay;
import SnakeGame.gui.Window;

public class App {
    public void game() {
        
        new Gameplay();
    }

    public static void main(String[] args) {
        new App().game();
    }
}
