/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SnakeGame;

import SnakeGame.gamelogic.Gameplay;

public class App {
    public static void main(String[] args) {
        new Gameplay();
    }
}
